#pragma once
#include "shading_kernel.cuh"
#include "containers.cuh"

namespace KittlesPT
{
	/* EASU stage
	*
	* This takes a reduced resolution source, and scales it up while preserving detail.
	*
	*/

	inline __device__ float3 FsrEasuCF(float2 p, const DeviceTextureBuffer& tex) {
		return make_float3(tex.textureReadBilinearUV(p, true));
	}

	/**** EASU ****/
	inline __device__ void FsrEasuCon(
		float4& con0,
		float4& con1,
		float4& con2,
		float4& con3,
		// This the rendered image resolution being upscaled
		float2 inputViewportInPixels,
		// This is the resolution of the resource containing the input image (useful for dynamic resolution)
		float2 inputSizeInPixels,
		// This is the display resolution which the input image gets upscaled to
		float2 outputSizeInPixels
	)
	{
		// Output integer position to a pixel position in viewport.
		con0 = make_float4(
			inputViewportInPixels.x / outputSizeInPixels.x,
			inputViewportInPixels.y / outputSizeInPixels.y,
			0.5 * inputViewportInPixels.x / outputSizeInPixels.x - 0.5,
			0.5 * inputViewportInPixels.y / outputSizeInPixels.y - 0.5
		);
		// Viewport pixel position to normalized image space.
		// This is used to get upper-left of 'F' tap.
		con1 = make_float4(1, 1, 1, -1) /
			make_float4(inputSizeInPixels.x, inputSizeInPixels.y, inputSizeInPixels.x, inputSizeInPixels.y);
		// Centers of gather4, first offset from upper-left of 'F'.
		//      +---+---+
		//      |   |   |
		//      +--(0)--+
		//      | b | c |
		//  +---F---+---+---+
		//  | e | f | g | h |
		//  +--(1)--+--(2)--+
		//  | i | j | k | l |
		//  +---+---+---+---+
		//      | n | o |
		//      +--(3)--+
		//      |   |   |
		//      +---+---+
		// These are from (0) instead of 'F'.
		con2 = make_float4(-1, 2, 1, 2) /
			make_float4(inputSizeInPixels.x, inputSizeInPixels.y, inputSizeInPixels.x, inputSizeInPixels.y);
		con3 = make_float4(0, 4, 0, 0) /
			make_float4(inputSizeInPixels.x, inputSizeInPixels.y, inputSizeInPixels.x, inputSizeInPixels.y);
	}

	// Filtering for a given tap for the scalar.
	inline __device__ void FsrEasuTapF(
		float3& aC, // Accumulated color, with negative lobe.
		float& aW, // Accumulated weight.
		float2 off, // Pixel offset from resolve position to tap.
		float2 dir, // Gradient direction.
		float2 len, // Length.
		float lob, // Negative lobe strength.
		float clp, // Clipping point.
		float3 c
	)
	{
		// Tap color.
		// Rotate offset by direction.
		float2 v = make_float2(dot(off, dir), dot(off, make_float2(-dir.y, dir.x)));
		// Anisotropy.
		v *= len;
		// Compute distance^2.
		float d2 = min(dot(v, v), clp);
		// Limit to the window as at corner, 2 taps can easily be outside.
		// Approximation of lancos2 without sin() or rcp(), or sqrt() to get x.
		//  (25/16 * (2/5 * x^2 - 1)^2 - (25/16 - 1)) * (1/4 * x^2 - 1)^2
		//  |_______________________________________|   |_______________|
		//                   base                             window
		// The general form of the 'base' is,
		//  (a*(b*x^2-1)^2-(a-1))
		// Where 'a=1/(2*b-b^2)' and 'b' moves around the negative lobe.
		float wB = .4 * d2 - 1.;
		float wA = lob * d2 - 1.;
		wB *= wB;
		wA *= wA;
		wB = 1.5625 * wB - .5625;
		float w = wB * wA;
		// Do weighted average.
		aC += c * w;
		aW += w;
	}

	//------------------------------------------------------------------------------------------------------------------------------
	// Accumulate direction and length.
	inline __device__ void FsrEasuSetF(
		float2& dir,
		float& len,
		float w,
		float lA, float lB, float lC, float lD, float lE
	)
	{
		// Direction is the '+' diff.
		//    a
		//  b c d
		//    e
		// Then takes magnitude from abs average of both sides of 'c'.
		// Length converts gradient reversal to 0, smoothly to non-reversal at 1, shaped, then adding horz and vert terms.
		float lenX = max(abs(lD - lC), abs(lC - lB));
		float dirX = lD - lB;
		dir.x += dirX * w;
		lenX = clamp(abs(dirX) / lenX, 0., 1.);
		lenX *= lenX;
		len += lenX * w;
		// Repeat for the y axis.
		float lenY = max(abs(lE - lC), abs(lC - lA));
		float dirY = lE - lA;
		dir.y += dirY * w;
		lenY = clamp(abs(dirY) / lenY, 0., 1.);
		lenY *= lenY;
		len += lenY * w;
	}

	//------------------------------------------------------------------------------------------------------------------------------
	inline __device__ void FsrEasuF(
		float3& pix,
		float2 ip, // Integer pixel position in output.
		// Constants generated by FsrEasuCon().
		float4 con0, // xy = output to input scale, zw = first pixel offset correction
		float4 con1,
		float4 con2,
		float4 con3,
		const DeviceTextureBuffer& texture
	)
	{
		//------------------------------------------------------------------------------------------------------------------------------
		// Get position of 'f'.
		float2 pp = ip * make_float2(con0.x, con0.y) + make_float2(con0.z, con0.w); // Corresponding input pixel/subpixel
		float2 fp = floorf(pp);// fp = source nearest pixel
		pp -= fp; // pp = source subpixel

		//------------------------------------------------------------------------------------------------------------------------------
		// 12-tap kernel.
		//    b c
		//  e f g h
		//  i j k l
		//    n o
		// Gather 4 ordering.
		//  a b
		//  r g
		float2 p0 = fp * make_float2(con1.x, con1.y) + make_float2(con1.z, con1.w);

		// These are from p0 to avoid pulling two constants on pre-Navi hardware.
		float2 p1 = p0 + make_float2(con2.x, con2.y);
		float2 p2 = p0 + make_float2(con2.z, con2.w);
		float2 p3 = p0 + make_float2(con3.x, con3.y);

		// TextureGather is not available
		float4 off = make_float4(-0.5, 0.5, -0.5, 0.5) * make_float4(con1.x, con1.x, con1.y, con1.y);
		// textureGather to texture offsets
		// x=west y=east z=north w=south
		float3 bC = FsrEasuCF(p0 + make_float2(off.x, off.w), texture); float bL = bC.y + 0.5 * (bC.x + bC.z);
		float3 cC = FsrEasuCF(p0 + make_float2(off.y, off.w), texture); float cL = cC.y + 0.5 * (cC.x + cC.z);
		float3 iC = FsrEasuCF(p1 + make_float2(off.x, off.w), texture); float iL = iC.y + 0.5 * (iC.x + iC.z);
		float3 jC = FsrEasuCF(p1 + make_float2(off.y, off.w), texture); float jL = jC.y + 0.5 * (jC.x + jC.z);
		float3 fC = FsrEasuCF(p1 + make_float2(off.y, off.z), texture); float fL = fC.y + 0.5 * (fC.x + fC.z);
		float3 eC = FsrEasuCF(p1 + make_float2(off.x, off.z), texture); float eL = eC.y + 0.5 * (eC.x + eC.z);
		float3 kC = FsrEasuCF(p2 + make_float2(off.x, off.w), texture); float kL = kC.y + 0.5 * (kC.x + kC.z);
		float3 lC = FsrEasuCF(p2 + make_float2(off.y, off.w), texture); float lL = lC.y + 0.5 * (lC.x + lC.z);
		float3 hC = FsrEasuCF(p2 + make_float2(off.y, off.z), texture); float hL = hC.y + 0.5 * (hC.x + hC.z);
		float3 gC = FsrEasuCF(p2 + make_float2(off.x, off.z), texture); float gL = gC.y + 0.5 * (gC.x + gC.z);
		float3 oC = FsrEasuCF(p3 + make_float2(off.y, off.z), texture); float oL = oC.y + 0.5 * (oC.x + oC.z);
		float3 nC = FsrEasuCF(p3 + make_float2(off.x, off.z), texture); float nL = nC.y + 0.5 * (nC.x + nC.z);

		//------------------------------------------------------------------------------------------------------------------------------
		// Simplest multi-channel approximate luma possible (luma times 2, in 2 FMA/MAD).
		// Accumulate for bilinear interpolation.
		float2 dir = make_float2(0);
		float len = 0.;

		FsrEasuSetF(dir, len, (1. - pp.x) * (1. - pp.y), bL, eL, fL, gL, jL);
		FsrEasuSetF(dir, len, pp.x * (1. - pp.y), cL, fL, gL, hL, kL);
		FsrEasuSetF(dir, len, (1. - pp.x) * pp.y, fL, iL, jL, kL, nL);
		FsrEasuSetF(dir, len, pp.x * pp.y, gL, jL, kL, lL, oL);

		//------------------------------------------------------------------------------------------------------------------------------
		// Normalize with approximation, and cleanup close to zero.
		float2 dir2 = dir * dir;
		float dirR = dir2.x + dir2.y;
		bool zro = dirR < (1.0 / 32768.0);
		dirR = inversesqrt(dirR);
		dirR = zro ? 1.0 : dirR;
		dir.x = zro ? 1.0 : dir.x;
		dir *= make_float2(dirR);
		// Transform from {0 to 2} to {0 to 1} range, and shape with square.
		len = len * 0.5;
		len *= len;
		// Stretch kernel {1.0 vert|horz, to sqrt(2.0) on diagonal}.
		float stretch = dot(dir, dir) / (max(abs(dir.x), abs(dir.y)));
		// Anisotropic length after rotation,
		//  x := 1.0 lerp to 'stretch' on edges
		//  y := 1.0 lerp to 2x on edges
		float2 len2 = make_float2(1. + (stretch - 1.0) * len, 1. - .5 * len);
		// Based on the amount of 'edge',
		// the window shifts from +/-{sqrt(2.0) to slightly beyond 2.0}.
		float lob = .5 - .29 * len;
		// Set distance^2 clipping point to the end of the adjustable window.
		float clp = 1. / lob;

		//------------------------------------------------------------------------------------------------------------------------------
		// Accumulation mixed with min/max of 4 nearest.
		//    b c
		//  e f g h
		//  i j k l
		//    n o
		float3 min4 = fminf(fminf(fC, gC), fminf(jC, kC));
		float3 max4 = fmaxf(fmaxf(fC, gC), fmaxf(jC, kC));
		// Accumulation.
		float3 aC = make_float3(0);
		float aW = 0.;
		FsrEasuTapF(aC, aW, make_float2(0, -1) - pp, dir, len2, lob, clp, bC);
		FsrEasuTapF(aC, aW, make_float2(1, -1) - pp, dir, len2, lob, clp, cC);
		FsrEasuTapF(aC, aW, make_float2(-1, 1) - pp, dir, len2, lob, clp, iC);
		FsrEasuTapF(aC, aW, make_float2(0, 1) - pp, dir, len2, lob, clp, jC);
		FsrEasuTapF(aC, aW, make_float2(0, 0) - pp, dir, len2, lob, clp, fC);
		FsrEasuTapF(aC, aW, make_float2(-1, 0) - pp, dir, len2, lob, clp, eC);
		FsrEasuTapF(aC, aW, make_float2(1, 1) - pp, dir, len2, lob, clp, kC);
		FsrEasuTapF(aC, aW, make_float2(2, 1) - pp, dir, len2, lob, clp, lC);
		FsrEasuTapF(aC, aW, make_float2(2, 0) - pp, dir, len2, lob, clp, hC);
		FsrEasuTapF(aC, aW, make_float2(1, 0) - pp, dir, len2, lob, clp, gC);
		FsrEasuTapF(aC, aW, make_float2(1, 2) - pp, dir, len2, lob, clp, oC);
		FsrEasuTapF(aC, aW, make_float2(0, 2) - pp, dir, len2, lob, clp, nC);
		//------------------------------------------------------------------------------------------------------------------------------
		// Normalize and dering.
		pix = fminf(max4, fmaxf(min4, aC / aW));
	}

	//void mainImage(float4& fragColor, float2 fragCoord)
	//{
	//	float3 c;
	//	float4 con0, con1, con2, con3;

	//	// "rendersize" refers to size of source image before upscaling.
	//	float2 rendersize = iChannelResolution[0].xy;
	//	FsrEasuCon(
	//		con0, con1, con2, con3, rendersize, rendersize, iResolution.xy
	//	);
	//	FsrEasuF(c, fragCoord, con0, con1, con2, con3);
	//	fragColor = make_float4(c, 1);
	//}
}

#define USE_FSR

__global__ void upscale(KittlesPT::DeviceTextureBuffer t_src, KittlesPT::DeviceTextureBuffer t_dst)
{
	using namespace KittlesPT;

	ShadingJob shading_job = getShadingJob(t_dst.dimensions);

	if (shading_job.is_invalid) {
		return;
	}
	float4 data;

#ifdef USE_FSR
	float3 c;
	float4 con0, con1, con2, con3;
	// "rendersize" refers to size of source image before upscaling.
	float2 rendersize = make_float2(t_src.dimensions);
	FsrEasuCon(
		con0, con1, con2, con3,
		rendersize, rendersize, make_float2(t_dst.dimensions)
	);
	FsrEasuF(c, make_float2(shading_job.pixel_coord),
		con0, con1, con2, con3, t_src);
	data = make_float4(c, 1);
#else
	float2 dst_uv = make_float2(shading_job.pixel_coord) / t_dst.dimensions;
	float2 src_pixel_coord = dst_uv * t_src.dimensions;

	data = t_src.textureReadBilinear(src_pixel_coord, true);
#endif // USE_FSR

	t_dst.textureWrite(data, shading_job.pixel_coord);
}

//RCAS--------------------------------



__global__ void sharpen(KittlesPT::DeviceTextureBuffer t_src, KittlesPT::DeviceTextureBuffer t_dst)
{
}